# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a76a88cb75bf535552e2c59b5ce173e7378ac29206fcc496dde2333d050702dbb8abcd3c786391bac286afcebffb2c74964f87600bd18658e24d3f59cfb4625

test:
  secret_key_base: 8309c281bac56501aac939f504b8d48c57fe29689bd95638a7b4b2a3d7693233ecf5cb4fc5597ed8583927a080483c007de5ed6a8c1f3b5d7bb6ebc8f4771848

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
